# Generated by Django 2.1 on 2018-09-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='release',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
