# Generated by Django 2.1 on 2018-09-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_auto_20180905_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
