# Generated by Django 2.1 on 2018-09-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='artwork',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='release',
            name='streaming_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
